version: 2

registries:
  azure-container-registry:
    type: docker-registry
    url: https://acrcontinuouspatchingdemo.azurecr.io/
    username: ${{ secrets.ACR_ADMIN_USERNAME }}
    password: ${{ secrets.ACR_ADMIN_PASSWORD }}

updates:
  - package-ecosystem: docker
    directory: "/deployments"
    registries: "*"
    schedule:
      interval: "daily"
