name: Deploy Azure Container Registry Image to Azure Kubernetes Service Cluster

on:
  push:
    branches:
      - main

permissions:
  id-token: write # Require write permission to Fetch an OIDC token.
  contents: read
  actions: read

jobs: 
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout GitHub repository
      uses: actions/checkout@v4

    - name: Azure CLI Login
      id: az-login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Set AKS cluster context
      id: aks-login
      uses: azure/aks-set-context@v4
      with:
        resource-group: ${{ secrets.AZURE_RESOURCE_GROUP }}
        cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}

    - name: Deploy to AKS cluster
      id: aks-deploy
      uses: Azure/k8s-deploy@v5
      with:
        action: deploy
        strategy: basic
        manifests: |
          deployments/nginx.yaml
